### ISSUE TITLE
$25 | Selection indicator is not displayed in some cases

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/navigation-component#62]
1. Click on Community -> Dashboard or My Profile, selection indicator disappears.
This also happens when the user is logged out and you click on Community -> Overview or How it Works

**Comment by SathyaJayabal** [comment]
[selection indicator bug.mov.zip](https://github.com/topcoder-platform/navigation-component/files/3968145/selection.indicator.bug.mov.zip)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues,The selection indicator is also not present when the user navigates to some pages that are not on the menu.

examples:
<img width="1404" alt="Screenshot 2019-12-17 at 11 20 42 AM" src="https://user-images.githubusercontent.com/58783823/70968525-757a1980-20bf-11ea-94ae-46b21972ce66.png">
<img width="1410" alt="Screenshot 2019-12-17 at 11 21 22 AM" src="https://user-images.githubusercontent.com/58783823/70968526-757a1980-20bf-11ea-989f-bba07c019f65.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , one more example of the selection indicator not displayed properly

On a tab size window, when you click on more->explore->programs, the selection indicator moves from more to Community
cc @nithyaasworld 
[selection indicator 62.mov.zip](https://github.com/topcoder-platform/navigation-component/files/3988947/selection.indicator.62.mov.zip)

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Any status on this one?

**Comment by LieutenantRoger** [comment]
Hi @luizrrodrigues 

Working on this ticket. Will submit Asap.

**Comment by LieutenantRoger** [comment]
Hi @luizrrodrigues 

Do you know how to resolve this issue ?  I only checked out the code and try to launch the community app, it used to be launchable, but I received the error like this now. 

https://take.ms/WGDkv

**Comment by luizrrodrigues** [comment]
What steps you followed to deploy and run app? Also you set the env vars shared in forum?

**Comment by LieutenantRoger** [comment]
Never mind, I have managed to launch the necessary page. The error I posted above appears some data incomplete in the dev env.

**Comment by luizrrodrigues** [comment]
You can run locally with Prod env data (is always better to me when test in my local)

**Comment by LieutenantRoger** [comment]
Can you take a look like this ?  I tried use npm start to launch it in production mode, but the page seemed not able to launch ; https://take.ms/rb5VY

**Comment by luizrrodrigues** [comment]
@LieutenantRoger try set port:
`export PORT=80`

**Comment by LieutenantRoger** [comment]
The data seemed not load still.  I can visit TonyJ in dev but not in prod environment: https://take.ms/AL6fm

**Comment by LieutenantRoger** [comment]
And in dev mode, both the my profile page and dash-board page won't load, I seemed stuck on verifying my solution

**Comment by LieutenantRoger** [comment]
https://take.ms/65T7f

**Comment by luizrrodrigues** [comment]
Use these step to deploy  / start:

```
npm install
npm run build
npm start
```

And make sure to use `node v8.16.0`

**Comment by LieutenantRoger** [comment]
I assume we can ignore the CI error ? as I didn't find a .circleci file, so not sure navigation-component should run though the CI after we made a commit.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Yep, ignore this for now.

**Comment by SathyaJayabal** [comment]
The selection indicator must not be displayed when  the user accesses a page that is not part of the menu.  example: https://www.topcoder.com/settings/profile
<img width="1424" alt="Screenshot 2020-01-21 at 2 33 42 PM" src="https://user-images.githubusercontent.com/58783823/72790221-38bfb600-3c5b-11ea-8d0a-a79b231f5cd8.png">

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Please check feedback above.

**Comment by LieutenantRoger** [comment]
Hi @luizrrodrigues  additional fix pushed to the MR: https://github.com/topcoder-platform/navigation-component/pull/85

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Please create a new MR.

**Comment by LieutenantRoger** [comment]
Ok, here it is: https://github.com/topcoder-platform/navigation-component/pull/145

I thought I have pushed the fix, looks the MR need to be re-created.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Yes, because old MR was merged. :)
Thanks.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Not working well:

Missing arrow:
![image](https://user-images.githubusercontent.com/7029641/73115832-caa11a80-3f0a-11ea-83ab-9ea4f4e6c436.png)

[Screen Recording 2020-01-25 at 00.38.16.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4111597/Screen.Recording.2020-01-25.at.00.38.16.mov.zip)

Showing arrow (need don't show here):
![image](https://user-images.githubusercontent.com/7029641/73115839-e4daf880-3f0a-11ea-8f06-5d4de82509ee.png)

**Comment by LieutenantRoger** [comment]
Could you please rephrase the requirement ?  I'm more confusing than before.

Based on what rule, the choosing arrow should display, thanks.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Based in your solution I have fixed the issue (just changed the right variables to show hide Arrow)

https://github.com/topcoder-platform/navigation-component/pull/145/commits/1db2f1d4c650f40ed5d519872bfd5dd791deac17

Thanks.

**Comment by LieutenantRoger** [comment]
Great, thanks.

**Comment by SathyaJayabal** [comment]
This issue still exists.
https://github.com/topcoder-platform/navigation-component/issues/62#issuecomment-567965305
But I will tag it with #101  as it seems related.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I think original issue was fixed here, if remain issue is related with "More" button, let close this one and track in #101

**Comment by SathyaJayabal** [comment]
Yes, I am just going to mark this as pass after I have linked the issue

**Comment by macs054** [comment]
Verified in Beta
![image](https://user-images.githubusercontent.com/1199534/75412250-dc883a00-595c-11ea-8288-c8ac02b192e2.png)  
![image](https://user-images.githubusercontent.com/1199534/75412257-e447de80-595c-11ea-9225-f4953fc1c7d8.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1439" alt="Screenshot 2020-02-28 at 8 44 40 AM" src="https://user-images.githubusercontent.com/58783823/75507256-98517400-5a06-11ea-9ad6-747ce7cfbee7.png">
